# Generated by Django 4.1 on 2022-09-06 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("the_weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city", options={"verbose_name_plural": "cities"},
        ),
    ]
